#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
RESOURCES_ROOT="$PROJECT_ROOT/SafariPTTheme/Extension/Resources"

usage() {
	printf '%s\n' "Usage: $0 [--dry-run] tracker.example.com [mirror.example.com ...]"
}

dry_run=0
if [ "$#" -gt 0 ] && [ "$1" = '--dry-run' ]; then
	dry_run=1
	shift
fi

if [ "$#" -eq 0 ]; then
	usage >&2
	exit 2
fi

TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT
DOMAINS_JSON="$TEMP_DIR/domains.json"

node - "$PROJECT_ROOT" "$DOMAINS_JSON" "$@" <<'NODE'
const fs = require('fs');
const vm = require('vm');

const projectRoot = process.argv[2];
const outputPath = process.argv[3];
const inputDomains = process.argv.slice(4);
const utilitySource = fs.readFileSync(`${projectRoot}/SafariPTTheme/Extension/Resources/domain-utils.js`, 'utf8');
const context = {};
vm.runInNewContext(utilitySource, context);

const utility = context.GPTUIThemeDomain;
const domains = [...new Set(inputDomains.map(utility.normalizeDomain))].sort();

if (domains.some((domain) => !utility.isValidDomain(domain))) {
  throw new Error('One or more domains are invalid.');
}

fs.writeFileSync(outputPath, JSON.stringify(domains), 'utf8');
NODE

if [ "$dry_run" -eq 1 ]; then
	printf '%s\n' 'Normalized domains:'
	node - "$DOMAINS_JSON" <<'NODE'
const fs = require('fs');
const domains = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
console.log(domains.join('\n'));
NODE
	exit 0
fi

node - "$PROJECT_ROOT" "$DOMAINS_JSON" <<'NODE'
const fs = require('fs');

const projectRoot = process.argv[2];
const domains = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'));
const resourcesRoot = `${projectRoot}/SafariPTTheme/Extension/Resources`;
const manifestPath = `${resourcesRoot}/manifest.json`;
const targetDomainsPath = `${resourcesRoot}/target-domains.js`;

const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
// Translation targets can be added at runtime, so the content script must be
// available before a domain has been saved in extension storage.
const matches = ['<all_urls>'];
manifest.content_scripts = manifest.content_scripts.map((script, index) => (
  index === 0 ? { ...script, matches } : script
));
fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

const configSource = [
  '(() => {',
  '  // Generated by Scripts/configure-domains.sh.',
  '  globalThis.GPTUIThemeConfig = Object.freeze({',
  `    domains: ${JSON.stringify(domains, null, 2).replace(/\n/g, '\n    ')}`,
  '  });',
  '})();',
  ''
].join('\n');
fs.writeFileSync(targetDomainsPath, configSource, 'utf8');
NODE

printf '%s\n' 'Configured domains in the manifest and target defaults.'
printf '%s\n' 'Run ./Scripts/validate-extension.sh and ./Scripts/build-extension.sh next.'
